### ISSUE TITLE
Configure SpotBugs and FindBugs with sarif reports

### ISSUE THREAD

**Issue by acbgbca** [acbgbca/pw-scraper#49]
We should configure SpotBugs and FindBugs with sarif reports, which we can then upload into GitHub.

See:
```
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif
```
